from langchain_core.documents import Document
from src.agent.state import AgentState
from src.doc_processing.hybrid_retrieval_pipeline import query_retrieval

def retriever_node(state: AgentState):
    """
    Bridge between the Agent State and the Hybrid Retrieval Pipeline.
    """
    # 1. Pull the query generated by your Router
    # (The router has already handled the standalone rewrite)
    search_query = state.get("query")

    print(f"--- RUNNING HYBRID RETRIEVAL FOR: {search_query} ---")

    # 2. Call your external pipeline
    # Expected output: list of dicts [{'content': '...', 'metadata': {...}}]
    retrieved_dicts = query_retrieval(search_query)
    i = 1
    # 3. Convert dicts to LangChain Documents
    # This ensures compatibility with your generator's d.metadata.get() logic
    langchain_docs = []
    for item in retrieved_dicts:
        doc = Document(
            # Use "text" because that's what's in your upload chunk
            page_content=item.get("text", ""), 
            
            # Use "meta" because your dict has 'meta': {...}
            metadata=item.get("meta", {})
        )
        langchain_docs.append(doc)
    # 4. Update the state
    return {"documents": langchain_docs}